name       : eviacam
version    : 2.1.2
release    : 4
source     :
    - https://github.com/cmauri/eviacam/archive/v2.1.2.tar.gz : 24127b7c40107477d351173b399909fa2d2c1f9a898b64712815a04c2c1a042d
license    : GPL-3.0
component  : desktop
summary    : Enable Viacam (eviacam) is a mouse replacement software that moves the
    pointer as you move your head.
description: |
    Enable Viacam (eviacam) is a mouse replacement software that moves the pointer as you move your head.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(ice)
    - pkgconfig(opencv)
    - pkgconfig(libv4l1)
    - pkgconfig(xtst)
    - wxwidgets-devel
setup      : |
    %autogen --disable-updates-check
build      : |
    %make
install    : |
    %make_install
