name       : eviacam
version    : 2.1.1
release    : 1
source     :
    - https://github.com/cmauri/eviacam/archive/v2.1.1.tar.gz : 5e7425658c8003e010e99d066088d58f287fba25d3def8ff71341cbf94b78520
license    : GPL-3.0
component  : desktop
summary    : Enable Viacam (eviacam) is a mouse replacement software that moves the pointer as you move your head.
description: |
    Enable Viacam (eviacam) is a mouse replacement software that moves the pointer as you move your head.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(ice)
    - pkgconfig(opencv)
    - pkgconfig(libv4l1)
    - pkgconfig(xtst)
    - wxwidgets-devel
setup      : |
    %autogen --disable-updates-check
build      : |
    %make
install    : |
    %make_install
