name       : eviacam
version    : 2.1.4
release    : 10
source     :
    - https://github.com/cmauri/eviacam/archive/refs/tags/v2.1.4.tar.gz : 0ed868e6f3f32fa48002ebc7cfbd58e1a0035ff954bb09adc4bc27cd3928cceb
license    : GPL-3.0-or-later
component  : desktop
summary    : Enable Viacam (eviacam) is a mouse replacement software that moves the pointer as you move your head
description: |
    Enable Viacam (eviacam) is a mouse replacement software that moves the pointer as you move your head.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(ice)
    - pkgconfig(opencv4)
    - pkgconfig(libv4l1)
    - pkgconfig(xtst)
    - wxwidgets-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-add-missing-includes.patch
    %patch -p1 < $pkgfiles/opencv4.patch
    sed -i '252s@1@0@' src/viacamcontroller.cpp
    %autogen --disable-updates-check
build      : |
    %make
install    : |
    %make_install
