name       : eviacam
version    : 2.1.3
release    : 5
source     :
    - https://github.com/cmauri/eviacam/archive/v2.1.3.tar.gz : bb7e2162e2b1b4e9a990e7f75e6b150b89b3c7b846f1f2925880e42894b9281d
license    : GPL-3.0
component  : desktop
summary    : Enable Viacam (eviacam) is a mouse replacement software that moves the pointer as you move your head
description: |
    Enable Viacam (eviacam) is a mouse replacement software that moves the pointer as you move your head.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(opencv)
    - pkgconfig(libv4l1)
    - pkgconfig(xtst)
    - wxwidgets-devel
setup      : |
    %autogen --disable-updates-check
build      : |
    %make
install    : |
    %make_install

